### ISSUE TITLE
grafana auto login

### ISSUE THREAD

**Issue by colorfulZebra** [Asiainfo-OCCI/OCCI_UI#1]
利用iframe嵌入grafana页面，希望直接显示dashboard页面，但是每次会被重定向到登录页面，需要自动登录才能直接进入dashboard页面

参考：
https://github.com/grafana/grafana/issues/3752

**Comment by colorfulZebra** [comment]
解决思路一 
根据grafana页面源代码
<pre><code>
a.login = function() {
    delete a.loginError, a.loginForm.$valid && c.post("/login", a.formModel).then(function(a) {
        var b = f.search();
        b.redirect && "/" === b.redirect[0] ? window.location.href = d.appSubUrl + b.redirect: a.redirectUrl ? window.location.href = a.redirectUrl: window.location.href = d.appSubUrl + "/"
    })  
},
a.init()
</code></pre>

POST请求/login并带上user和password，然后修改iframe的src跳转

结论：
失败。

**Comment by colorfulZebra** [comment]
解决思路二
利用basic_auth。

参考
Grafana配置： http://docs.grafana.org/tutorials/authproxy/
Nginx配置： https://community.grafana.com/t/how-to-use-auth-proxy-with-nginx/2257/3

结论：
配置成功后浏览器第一次访问需要输入用户和密码来和服务器端存储的匹配，之后才能实现免密登录。
不够完善

**Comment by cybfly** [comment]
可以通过设置允许匿名登录来实现只查看的效果，不过这样匿名用户查看的范围比较广
[auth.anonymous]
# enable anonymous access
enabled = true

你的第二种方法我尝试了一下，感觉没有效果，不知是哪里没配置对
Grafana.conf
![image](https://user-images.githubusercontent.com/1582140/40064376-f57726e8-5891-11e8-8053-710f661f945b.png)

Nginx的conf
![image](https://user-images.githubusercontent.com/1582140/40064312-d2e6ad2e-5891-11e8-811f-c12bb0dd6da3.png)

**Comment by colorfulZebra** [comment]
项目迁移到Gitlab，关闭所有issue
